### ISSUE TITLE
plugin crashes when rate_limiter with action to "log_only" is set

### ISSUE THREAD

**Issue by rayzorinc** [fastly/terraform-provider-fastly#703]
### Terraform Version

```shell
v1.0.11
```

### fastly provider version

```shell
4.3.3
```

### Affected Fastly Terraform Resource(s)

- `fastly_service_vcl`
  -  `rate_limiter`

When creating a `rate_limiter` with option of `log_only` for `action`, the plugin crashed every time trying to run apply even tho it was fine running the plan.

### Terraform Configuration Files

```hcl
       rate_limiter {
           action               = "log_only"
           client_key           = "client.ip,req.http.User-Agent"
           http_methods         = "GET,PUT,TRACE,POST,HEAD,DELETE,PATCH,OPTIONS"
           logger_type          = "datadog"
           name                 = "rate limit"
           penalty_box_duration = 2
           ratelimiter_id       = (known after apply)
           rps_limit            = 1000
           window_size          = 60
       }

```

### Expected Behavior

 Terraform applied successfully

### Actual Behavior

Plugin crashed hard

### Debug Output (optional)

```
module.test_service.fastly_service_vcl.service: Modifying... [id=3B......]
╷
│ Error: Plugin did not respond
│
│   with module.test_service.fastly_service_vcl.service,
│   on ../shared/modules/fastly_service/main.tf line 165, in resource "fastly_service_vcl" "service":
│  165: resource "fastly_service_vcl" "service" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-fastly_v4.3.3 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 86 [running]:
github.com/fastly/terraform-provider-fastly/fastly.(*RateLimiterAttributeHandler).buildUpdateERLInput(0x0?, {0xc000294678?, 0x0?}, {0x0?, 0x0?}, 0x0?, 0x0?, 0x0?)
	github.com/fastly/terraform-provider-fastly/fastly/block_fastly_service_ratelimiter.go:394 +0x90c
github.com/fastly/terraform-provider-fastly/fastly.(*RateLimiterAttributeHandler).Update(0x19a6f40?, {0xc000153d60?, 0x0?}, 0xc000598c00, 0xc000150100?, 0xc0003efcc0?, 0x54, 0x19e7e26?)
	github.com/fastly/terraform-provider-fastly/fastly/block_fastly_service_ratelimiter.go:243 +0x36f
github.com/fastly/terraform-provider-fastly/fastly.(*blockSetAttributeHandler).Process(0xc000031b90, {0x1b34588, 0xc00069c060}, 0x151?, 0xc0008025f0?, 0x225b108?)
	github.com/fastly/terraform-provider-fastly/fastly/service_crud_attribute_definition.go:121 +0x3dd
github.com/fastly/terraform-provider-fastly/fastly.resourceServiceUpdate({0x1b34588, 0xc00069c060}, 0xc000598c00, {0x1874aa0?, 0xc000290188}, {0x1b31350, 0x205a9a0})
	github.com/fastly/terraform-provider-fastly/fastly/base_fastly_service.go:400 +0x1a07
github.com/fastly/terraform-provider-fastly/fastly.resourceUpdate.func1({0x1b34588?, 0xc00069c060?}, 0x0?, {0x1874aa0?, 0xc000290188?})
	github.com/fastly/terraform-provider-fastly/fastly/base_fastly_service.go:216 +0x35
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc0000a5b20, {0x1b345c0, 0xc000284510}, 0xd?, {0x1874aa0, 0xc000290188})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:741 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0000a5b20, {0x1b345c0, 0xc000284510}, 0xc000401380, 0xc0000c0480, {0x1874aa0, 0xc000290188})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:847 +0x82c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000d9e0, {0x1b345c0?, 0xc0001ebfb0?}, 0xc0002c4410)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0000a3680, {0x1b345c0?, 0xc0001ea120?}, 0xc000592230)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x19a6de0?, 0xc0000a3680}, {0x1b345c0, 0xc0001ea120}, 0xc000592000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000001e0, {0x1b380c0, 0xc0002a09c0}, 0xc0007ca000, 0xc000412720, 0x2062980, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1340 +0xd13
google.golang.org/grpc.(*Server).handleStream(0xc0000001e0, {0x1b380c0, 0xc0002a09c0}, 0xc0007ca000, 0x0)
	google.golang.org/grpc@v1.51.0/server.go:1713 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-fastly_v4.3.3 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

### Steps to Reproduce

1. `terraform apply`

**Comment by Integralist** [comment]
Thanks @rayzorinc for opening this issue. 

Apologies for not replying sooner but it seems to have slipped past me (we have Slack channels notifying us of new issues and it seems this issue was never reported there either).

I'll dig into this and get back to you.
